# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rec.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trec.proto\x12\x03rec\"\x9f\x02\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nlast_login\x18\x02 \x01(\t\x12\x14\n\x0cis_superuser\x18\x03 \x01(\x05\x12\x10\n\x08is_staff\x18\x04 \x01(\x05\x12\x11\n\tis_active\x18\x05 \x01(\x05\x12\x13\n\x0b\x64\x61te_joined\x18\x06 \x01(\t\x12\x16\n\x0elast_seen_date\x18\x07 \x01(\t\x12\x0c\n\x04yaoi\x18\x08 \x01(\x05\x12\r\n\x05\x61\x64ult\x18\t \x01(\x05\x12\x12\n\npreference\x18\n \x01(\x05\x12\x11\n\tis_banned\x18\x0b \x01(\x05\x12\x15\n\x08\x62irthday\x18\x0c \x01(\tH\x00\x88\x01\x01\x12\x0b\n\x03sex\x18\r \x01(\x05\x12\x12\n\nis_premium\x18\x0e \x01(\x05\x42\x0b\n\t_birthday\"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x46\n\nRecService\x12\x38\n\x07GetUser\x12\x18.rec.UserRetrieveRequest\x1a\x11.rec.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERRESPONSE']._serialized_start=19
  _globals['_USERRESPONSE']._serialized_end=306
  _globals['_USERRETRIEVEREQUEST']._serialized_start=308
  _globals['_USERRETRIEVEREQUEST']._serialized_end=341
  _globals['_RECSERVICE']._serialized_start=343
  _globals['_RECSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
