# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\" \n\x0cTitleRequest\x12\x10\n\x08title_id\x18\x01 \x01(\x05\"*\n\x16RecommendationResponse\x12\x10\n\x08item_ids\x18\x01 \x03(\x05\"%\n\x0cTrainRequest\x12\x15\n\rforce_retrain\x18\x01 \x01(\x08\"B\n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\x32\x97\x02\n\x0bRecommender\x12_\n\x16GetUserRecommendations\x12\x1c.recommendations.UserRequest\x1a\'.recommendations.RecommendationResponse\x12Z\n\x10GetTitleRelevant\x12\x1d.recommendations.TitleRequest\x1a\'.recommendations.RecommendationResponse\x12K\n\nTrainModel\x12\x1d.recommendations.TrainRequest\x1a\x1e.recommendations.TrainResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=42
  _globals['_USERREQUEST']._serialized_end=72
  _globals['_TITLEREQUEST']._serialized_start=74
  _globals['_TITLEREQUEST']._serialized_end=106
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=108
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=150
  _globals['_TRAINREQUEST']._serialized_start=152
  _globals['_TRAINREQUEST']._serialized_end=189
  _globals['_TRAINRESPONSE']._serialized_start=191
  _globals['_TRAINRESPONSE']._serialized_end=257
  _globals['_RECOMMENDER']._serialized_start=260
  _globals['_RECOMMENDER']._serialized_end=539
# @@protoc_insertion_point(module_scope)
